(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(evil-want-Y-yank-to-eol nil)
 '(package-selected-packages
   (quote
    (org-journal nov esxml org-roam emacsql-sqlite3 emacsql web-mode import-js grizzl emmet-mode add-node-modules-path tide typescript-mode guide-key web-beautify prettier-js nodejs-repl livid-mode skewer-mode simple-httpd json-navigator hierarchy json-mode json-snatcher json-reformat js2-refactor multiple-cursors js2-mode js-doc zotxt deferred yasnippet-snippets helm-company helm-c-yasnippet fuzzy company-statistics company auto-yasnippet yasnippet ac-ispell auto-complete pdfgrep treemacs-magit magit git-commit with-editor transient doom-themes org-ref pdf-tools key-chord ivy helm-bibtex bibtex-completion biblio parsebib biblio-core tablist org-noter interleave doom-modeline shrink-path writeroom-mode visual-fill-column treemacs-projectile treemacs-persp treemacs-icons-dired treemacs-evil treemacs ht pfuture symon symbol-overlay string-inflection spaceline-all-the-icons all-the-icons memoize powerline password-generator spinner overseer org-superstar org-cliplink org-brain nameless parent-mode helm-xref helm-purpose window-purpose imenu-list helm-org-rifle helm-org helm-ls-git flycheck-package package-lint flycheck let-alist flycheck-elsa flx f evil-textobj-line evil-org evil-lion evil-goggles evil-cleverparens smartparens anzu emr iedit clang-format projectile paredit list-utils pkg-info epl editorconfig dash s devdocs centered-cursor-mode packed helm avy helm-core popup hydra lv hybrid-mode font-lock+ evil goto-chg undo-tree dotenv-mode bind-map bind-key async org-projectile org-category-capture org-present org-pomodoro alert log4e gntp org-mime org-download mmm-mode markdown-toc markdown-mode htmlize gnuplot gh-md ws-butler winum which-key volatile-highlights vi-tilde-fringe uuidgen use-package toc-org spaceline restart-emacs request rainbow-delimiters popwin persp-mode pcre2el paradox org-plus-contrib org-bullets open-junk-file neotree move-text macrostep lorem-ipsum linum-relative link-hint indent-guide hungry-delete hl-todo highlight-parentheses highlight-numbers highlight-indentation helm-themes helm-swoop helm-projectile helm-mode-manager helm-make helm-flx helm-descbinds helm-ag google-translate golden-ratio flx-ido fill-column-indicator fancy-battery eyebrowse expand-region exec-path-from-shell evil-visualstar evil-visual-mark-mode evil-unimpaired evil-tutor evil-surround evil-search-highlight-persist evil-numbers evil-nerd-commenter evil-mc evil-matchit evil-lisp-state evil-indent-plus evil-iedit-state evil-exchange evil-escape evil-ediff evil-args evil-anzu eval-sexp-fu elisp-slime-nav dumb-jump diminish define-word column-enforce-mode clean-aindent-mode auto-highlight-symbol auto-compile aggressive-indent adaptive-wrap ace-window ace-link ace-jump-helm-line))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
